name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: environment.yml
        auto-activate-base: false
    - name: Tests
      shell: bash -l {0}
      run: |
        conda install -c conda-forge jupyter papermill
        papermill 1-electronic-convergence.ipynb 1-electronic-convergence-out.ipynb -k "python3"
        papermill 2-dft-energy-precision.ipynb 2-dft-energy-precision-out.ipynb -k "python3"
        papermill 3-ev-curve.ipynb 3-ev-curve-out.ipynb -k "python3"
        papermill 4-phonons.ipynb 4-phonons-out.ipynb -k "python3"
